# Generated by Django 4.2.4 on 2023-08-23 08:53

import cloudinary.models
from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, validators=[users.models.validate_file_size], verbose_name='image'),
        ),
    ]
