# Generated by Django 4.2.3 on 2023-07-29 07:16

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null=True, upload_to='users/images/', validators=[users.models.validate_file_size]),
        ),
    ]
