# Generated by Django 4.2.4 on 2023-08-23 08:53

import cloudinary.models
from django.db import migrations
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[recipes.validators.validate_file_size], verbose_name='image'),
        ),
    ]
