# Generated by Django 4.2.3 on 2023-07-30 07:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('recipe', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('recipe', 'author')},
        ),
    ]
